version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: goexpense
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
      